blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^more/', include('posts.urls', namespace="more")),

]

if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^anything/$', views.some_function, name="anything"),
    url(r'^list/$', views.post_list, name="list"),
    url(r'^detail/(?P<post_id>\d+)/$', views.post_detail, name="detail"),

    url(r'^create/$', views.post_create, name="create"),
    url(r'^update/(?P<post_id>\d+)/$', views.post_update, name="update"),
    url(r'^delete/(?P<post_id>\d+)/$', views.post_delete, name="delete"),
    url(r'^random/$', views.random, name="random"),

]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Post(models.Model):
	title = models.CharField(max_length=120)
	author = models.ForeigonKey(User, default=1)
	slug = models.SlugField(unique=True)
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	img = models.ImageField(null=True, blank=True, upload_to="post_images")

	def __str__(self):
		return self.title

	def get_detail_url(self):
		return reverse("more:detail", kwargs={"post_id":self.id})

	class Meta:
		ordering = ['title']

def create_slug(instance, new_slug=None):
	slug_value = slugify(instance.title)
	if new_slug is not None:
		slug_value = new_slug

	query = Post.objects.filter(slug=slug_value)
	if query.exists():
		slug_value = "%s-%s"%(slug_value, query.last().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_function(*args **kwargs):
	instance = kwargs['instance']
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_function, sender=Post)	

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'img']
		

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404

def random(request):
    return render(request, 'random.html')

def post_create(request):
    if not request.user.is_staff:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        messages.success(request, "Awesome, you just added a blog post!")
        return redirect("more:list")
    context = {
        "form": form
    }
    return render(request, 'post_create.html', context)

def post_update(request, post_id):
    item = Post.objects.get(id=post_id)
    form = PostForm(request.POST or None, request.FILES or None, instance=item)
    if form.is_valid():
        form.save()
        messages.info(request, "Hey, you just changed a blog post!")
        return redirect("more:detail", post_id=item.id)
    context = {
        "form": form,
        "item":item,
    }
    return render(request, 'post_update.html', context)

def post_delete(request, post_id):
    Post.objects.get(id=post_id).delete()
    messages.warning(request, "Noooooooooo!")
    return redirect("more:list")

def some_function(request):
    some_dictionary = {
        "some_key": "with a random value",
    }
    return render(request, "something.html", some_dictionary)


def post_list(request):
    objects = Post.objects.all()
    # objects = Post.objects.all().order_by('title', 'id')
    paginator = Paginator(objects, 5)

    number = request.GET.get('page')

    try:
        objects = paginator.page(number)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    context = {
        "post_items": objects,
    }
    return render(request, "list.html", context)

def post_detail(request, post_id):
    # item = Post.objects.get(id=1000)
    item = get_object_or_404(Post, id=post_id)
    context = {
        "item": item,
    }
    return render(request, "detail.html", context)

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>
		{% block heading %}
			
		{% endblock heading %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

{% include "messages.html" %}

<div class="container">
{% block content %}
	
{% endblock content %}
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
		$(function () {
	  $('[data-toggle="popover"]').popover()
	})

</script>
</body>
</html>

posts/templates/detail.html
{% extends "base.html" %}
{% block heading %}
	Detail
{% endblock heading %}

{% block content %}
	<ul>
		<li>{{item.title}}</li>
		<li>{{item.content}}</li>
		<li>{{item.id}}</li>
	</ul>
{% endblock content %}

posts/templates/list.html
{% extends "base.html" %}
{% block heading %}
	List
{% endblock heading %}

{% block content %}

	<div class="jumbotron">
		<h1 class="display-3">These are my posts!</h1>
			<a class="btn btn-primary btn-lg" href="{% url 'more:create' %}" role="button">Create</a>
			<br><br>
			<button type="button" class="btn btn-success btn-lg btn-block" data-toggle="popover" title="IMPORTANT MESSAGE!!!" data-content="If you're reading this right now you should know that I'm really bored and you're a noob! :)">Click Me!</button>
		</p>
	</div>
	
	<div class="row">
	{% for item in post_items %}
		<div class="card col-xs-12 col-md-4" style="width: 20rem;">
			{% if item.img %}
				<img class="card-img-top" src="{{item.img.url}}" alt="Card image cap">
			{% endif %}
			<div class="card-body">
				<h4 class="card-title">{{item.title}} <small>{{item.created|timesince}}</small></h4>
				<p class="card-text">{{item.content|linebreaks|truncatechars:30}}</p>
				<a href="{% url 'more:detail' post_id=item.id %}" class="btn btn-info">Read More...</a>
				<a href="{% url 'more:update' post_id=item.id %}" class="btn btn-warning">Update</a>
				<a href="{% url 'more:delete' post_id=item.id %}" class="btn btn-danger">Delete</a>

			</div>
		</div>
	{% endfor %}
	</div>
	<div class="pagination">
    <span class="step-links">
        {% if post_items.has_previous %}
            <a href="?page={{ post_items.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_items.number }} of {{ post_items.paginator.num_pages }}.
        </span>

        {% if post_items.has_next %}
            <a href="?page={{ post_items.next_page_number }}">next</a>
        {% endif %}
    </span>
	</div>
{% endblock content %}

posts/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

posts/templates/post_create.html
{% extends "base.html" %}
{% block heading %}
	Create
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:create' %}" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Create">
	</form>
{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% block heading %}
	Update
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:update' post_id=item.id %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update">
	</form>
{% endblock content %}
</html>

posts/templates/random.html
{% extends "base.html" %}


{% block content %}
  
<style>
  .blue{
    background-color: blue;
    color: white;
  }
  .green{
    background-color: green;
    color: white;
  }
</style>


<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 blue">heloo</div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 green">heloo</div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 blue">heloo</div>
</div>


{% endblock content %}

posts/templates/something.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	{{some_key}}
</body>
</html>

posts/templates/temp1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>

posts/templates/temp2.html
</title>
</head>
<body>
	
{% include "messages.html" %}

posts/templates/temp3.html
</body>
</html>